import { useNavigate, Link } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

const H = ({ children }) => (
  <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '19px', margin: '28px 0 10px' }}>{children}</h2>
)
const P = ({ children }) => (
  <p style={{ fontSize: '14px', lineHeight: 1.7, color: 'var(--charcoal-soft)', marginBottom: '14px' }}>{children}</p>
)
const UL = ({ children }) => (
  <ul style={{ fontSize: '14px', lineHeight: 1.7, color: 'var(--charcoal-soft)', paddingLeft: '20px', marginBottom: '14px' }}>{children}</ul>
)

export default function Privacy() {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100dvh', background: 'var(--sand)' }}>
      <div style={{
        background: 'var(--white)', borderBottom: '1px solid var(--sand-dark)',
        padding: '16px 24px', position: 'sticky', top: 0, zIndex: 50,
        display: 'flex', alignItems: 'center', gap: '16px',
      }}>
        <button onClick={() => navigate(-1)} style={{
          background: 'none', border: 'none', cursor: 'pointer',
          color: 'var(--warm-gray)', display: 'flex',
        }}>
          <ChevronLeft size={24} />
        </button>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: '22px', fontWeight: 600 }}>
          Privacy Policy
        </h1>
      </div>

      <div style={{ maxWidth: '680px', margin: '0 auto', padding: '24px' }}>
        <div className="card">
          <p style={{ fontSize: '13px', color: 'var(--warm-gray)', marginBottom: '20px' }}>
            Last updated: [DATE]
          </p>

          <P>
            This Privacy Policy explains how Cuna ("Cuna," "we," "us," or "our") collects, uses,
            shares, and protects your information when you use the Cuna website, application, and
            related services (the "Service"). By using the Service, you agree to this Privacy Policy.
          </P>
          <P>
            Your use of the Service is also governed by our{' '}
            <Link to="/terms" style={{ color: 'var(--terracotta)', fontWeight: 600 }}>Terms of Service</Link>.
            If you have questions or requests about your information, contact us at{' '}
            <strong>Info@SLRGRP.com</strong>.
          </P>

          <H>1. Information We Collect</H>
          <P><strong>Information you provide to us:</strong></P>
          <UL>
            <li><strong>Account information</strong> — your email address, password (stored in encrypted form by our authentication provider), name, phone number, and whether you register as a Renter or a Poster.</li>
            <li><strong>Renter profile and search preferences</strong> — such as budget range, number of bedrooms, minimum square footage, and preferred neighborhoods.</li>
            <li><strong>Listings</strong> — if you are a Poster: property addresses, prices, fees, descriptions, photos, availability, and related listing details. Listings are shown to other users of the Service; do not include information in a listing that you don't want displayed publicly.</li>
            <li><strong>Messages</strong> — the content of messages you exchange with matched users through the Service.</li>
            <li><strong>Communications with us</strong> — anything you send to our contact email.</li>
          </UL>
          <P><strong>Information collected automatically:</strong></P>
          <UL>
            <li><strong>Activity on the Service</strong> — such as the listings you view, like ("swipe right"), pass on ("swipe left"), your matches, and when you use features of the Service.</li>
            <li><strong>Technical and log information</strong> — such as IP address, browser and device type, and usage logs generated by our hosting and infrastructure providers in the ordinary course of operating the Service.</li>
          </UL>
          <P>We do not currently use advertising trackers or sell advertising based on your data.</P>

          <H>2. How We Use Your Information</H>
          <P>We use your information to:</P>
          <UL>
            <li>Create and maintain your account and authenticate you;</li>
            <li>Operate the core features of the Service — showing listings that match your search preferences, recording your swipes, creating matches, and delivering messages between matched users;</li>
            <li>Display Poster listing information (including disclosed fees) to Renters;</li>
            <li>Send service emails, such as password reset emails;</li>
            <li>Respond to your questions, reports, and requests;</li>
            <li>Maintain the safety and integrity of the Service, including investigating suspected fraud, fake listings, or violations of our Terms of Service;</li>
            <li>Comply with legal obligations.</li>
          </UL>

          <H>3. How Your Information Is Shared</H>
          <P>We do <strong>not</strong> sell your personal information. We share information only in these circumstances:</P>
          <UL>
            <li><strong>With other users, as part of how the Service works.</strong> Your listings (if you are a Poster) are visible to Renters using the Service. When two users match, each can see the other's relevant profile information (such as name) and exchange messages. Contact details associated with a listing may be visible to matched Renters.</li>
            <li><strong>With service providers.</strong> We use third-party infrastructure providers to operate the Service — including Supabase (database, authentication, and file storage) and Vercel (hosting). These providers process data on our behalf and are bound by their own security and privacy commitments.</li>
            <li><strong>For legal reasons.</strong> We may disclose information if required by law, subpoena, or court order, or where we believe disclosure is necessary to protect the rights, safety, or property of Cuna, our users, or the public.</li>
            <li><strong>In a business transfer.</strong> If Cuna's business is reorganized (for example, into a newly formed LLC), or is merged, acquired, or sold, your information may be transferred as part of that transaction. This Privacy Policy would continue to apply.</li>
          </UL>

          <H>4. Data Retention</H>
          <P>
            We keep your information for as long as your account is active or as needed to operate the
            Service. If you delete your account (or ask us to), we will delete your profile,
            preferences, swipes, matches, messages, and uploaded photos, except where we need to retain
            limited information to comply with legal obligations, resolve disputes, or enforce our
            agreements.
          </P>

          <H>5. Your Choices and Rights</H>
          <UL>
            <li><strong>Access and update.</strong> You can view and update your profile and search preferences in the app.</li>
            <li><strong>Delete your account and data.</strong> Email <strong>Info@SLRGRP.com</strong> from the email address on your account and request deletion. We will delete your account and associated personal information as described above, within a reasonable time.</li>
            <li><strong>Email communications.</strong> Service emails (such as password resets) are part of operating your account. We do not currently send marketing emails; if we ever do, they will include an unsubscribe option.</li>
          </UL>
          <P>
            Depending on where you live, you may have additional privacy rights under applicable law.
            To exercise any privacy right, contact us at <strong>Info@SLRGRP.com</strong>.
          </P>

          <H>6. Security</H>
          <P>
            We take reasonable measures to protect your information, including encrypted password
            storage, access controls, and database-level security rules that restrict which users can
            read which data. No system is perfectly secure, however, and we cannot guarantee absolute
            security. Please use a strong, unique password and notify us immediately at{' '}
            <strong>Info@SLRGRP.com</strong> if you suspect unauthorized access to your account.
          </P>

          <H>7. Children's Privacy</H>
          <P>
            The Service is for users 18 and older. We do not knowingly collect personal information
            from anyone under 18 (and in no event from children under 13). If we learn we have
            collected personal information from someone under 18, we will delete it. If you believe a
            minor has provided us information, contact us at <strong>Info@SLRGRP.com</strong>.
          </P>

          <H>8. Users Outside the United States</H>
          <P>
            The Service is operated from the United States and intended for users in the United States.
            If you use the Service from elsewhere, you understand that your information will be
            processed and stored in the United States.
          </P>

          <H>9. Changes to This Policy</H>
          <P>
            We may update this Privacy Policy from time to time. If we make material changes, we will
            provide notice through the Service or by email, and update the "Last updated" date above.
            Your continued use of the Service after changes take effect constitutes acceptance of the
            updated policy.
          </P>

          <H>10. Contact</H>
          <P>Questions, requests, or concerns about your privacy: <strong>Info@SLRGRP.com</strong></P>
        </div>
      </div>
    </div>
  )
}
